# Generated by Django 4.2.11 on 2024-03-21 15:15

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('titulo_proyecto', models.CharField(help_text='Titulo principal. Maximo 30 caracteres. ', max_length=30)),
                ('fecha_publicacion', models.DateField(help_text='Fecha de publicacion del post.')),
                ('autor', models.CharField(blank=True, help_text='Nombre del autor. -Opcional ', max_length=30, null=True)),
                ('descripcion_proyecto', wagtail.fields.RichTextField(blank=True, help_text='Escriba aqui el contenido de su proyecto. Maximo 5000 caracteres.', max_length=5000)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ImagenFondoBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('imagen_proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='img_project', to='projects.blogpost')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
