# Generated by Django 4.2.11 on 2024-03-21 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='client',
            field=models.CharField(help_text='Nombre del cliente.', max_length=35, null=True),
        ),
    ]
