# Generated by Django 4.2.11 on 2024-04-01 20:24

from django.db import migrations, models
import django_extensions.db.fields
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_blogpost_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=255)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='nombre_categoria')),
            ],
            options={
                'verbose_name_plural': 'Categorias Proyectos',
                'ordering': ['nombre_categoria'],
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='categoria',
            field=modelcluster.fields.ParentalManyToManyField(to='projects.categorias'),
        ),
    ]
