version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: comunix_db
      POSTGRES_USER: comunix_user
      POSTGRES_PASSWORD: comunix_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app  # Asegúrate de que esta línea esté correctamente alineada con la estructura de directorios
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://comunix_user:comunix_password@db:5432/comunix_db

volumes:
  postgres_data:
